version: '2.1'
services:
  rabbitmq:
    ports:
      - 5672:5672

  config:
    build: config
    ports:
      - 8888:8888

  registry:
    build: registry

  gateway:
    build: gateway

  auth-service:
    build: auth-service
    ports:
      - 5000:5000

  auth-mongodb:
    build: mongodb
    ports:
      - 25000:27017

  account-mongodb:
    build: mongodb
    ports:
      - 26000:27017

  statistics-mongodb:
    build: mongodb
    ports:
      - 27000:27017

  notification-mongodb:
    build: mongodb
    ports:
      - 28000:27017

  monitoring:
    build: monitoring

  turbine-stream-service:
    build: turbine-stream-service