---
apiVersion: v1
kind: Service
metadata:
  name: account-mongodb
  labels:
    project: piggymetrics
    tier: database
    app: account-mongodb
spec:
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
  selector:
    project: piggymetrics
    tier: database
    app: account-mongodb
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: account-mongodb
  labels:
    project: piggymetrics
    tier: database
    app: account-mongodb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        project: piggymetrics
        tier: database
        app: account-mongodb
    spec:
      containers:
      - name: account-mongodb
        env:
        - name: INIT_DUMP
          value: account-service-dump.js
        - name: MONGODB_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: piggymetrics
              key: account_mongodb_password
        ports:
          - containerPort: 27017
        image: afermon/piggymetrics-mongodb
      restartPolicy: Always
