---
apiVersion: v1
kind: Secret
metadata:
  name: piggymetrics
type: Opaque
data:  #Replace default values. This is only meant to create the structure.
  config_service_password: Q09ORklHX1NFUlZJQ0VfUEFTU1dPUkQ=
  auth_mongodb_password: QVVUSF9NT05HT0RCX1BBU1NXT1JE
  notification_service_password: Tk9USUZJQ0FUSU9OX1NFUlZJQ0VfUEFTU1dPUkQ=
  notification_mongodb_password: Tk9USUZJQ0FUSU9OX01PTkdPREJfUEFTU1dPUkQ=
  statistics_service_password: U1RBVElTVElDU19TRVJWSUNFX1BBU1NXT1JE
  statistics_mongodb_password: U1RBVElTVElDU19NT05HT0RCX1BBU1NXT1JE
  account_service_password: QUNDT1VOVF9TRVJWSUNFX1BBU1NXT1JE
  account_mongodb_password: QUNDT1VOVF9NT05HT0RCX1BBU1NXT1JE
  notification_email_host: c210cC5nbWFpbC5jb20=
  notification_email_port: NDY1
  notification_email_user: ZGV2LXVzZXI=
  notification_email_pass: ZGV2LXBhc3N3b3Jk
